version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/GLOGG
    overwrite: yes
file_exists_behavior: OVERWRITE
permissions:
  - object: /home/ubuntu/GLOGG/
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 100
      runas: ubuntu