name: Build and Deploy to EC2

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Generate Gradle Wrapper
      run: gradle wrapper
      working-directory: path/to/your/project
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ./server
    - name: Change to project directory
      run: cd path/to/your/project
    - name: Build with Gradle
      run: ./gradlew clean build --exclude-task test
