name: NodeJS with Grunt

on:
  push:
    branches: ["main", "develop"]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CI: false
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        working-directory: client
        run: |
          npm install
          npm run build

      - name: Deploy build outputs
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          source: "build/*"
          strip_components: 1
          target: "/var/www/html/"
